server:
  port: 8210
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 50000
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.149.88
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    publisher-returns: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8