server:
  port: 8212
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 50000
spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.149.88
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-order?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: 121233Syy,.
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 5
      minimum-idle: 3
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

weixin:

  appid: wxcc651fcbab275e33
  partner: 1481962542
  partnerkey: MXb72b9RfshXZD4FRGV5KLqmv5bx9LT9
  notifyurl: http://gmall-prod.atguigu.cn/api/payment/weixin/notify
  cert: D:\yygh_work\yygh_parent\service\service-order\src\main\resources\apiclient_cert.p12